-- Supabase Schema for INDOTECH Dispatch Management System

-- 1. Profiles Table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Admin', 'Power User', 'Normal User')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Work Orders Table
CREATE TABLE IF NOT EXISTS public.work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_num TEXT NOT NULL UNIQUE,
    customer TEXT NOT NULL,
    rating TEXT,
    type TEXT,
    site TEXT,
    shift TEXT,
    status TEXT DEFAULT 'Pending',
    priority TEXT DEFAULT 'Normal',
    order_date TEXT,
    dispatch_date TEXT,
    remarks TEXT,
    vehicles TEXT[] DEFAULT '{}',
    job_serial_no TEXT,
    capacity_range TEXT,
    ref_doc TEXT,
    export_domestic TEXT DEFAULT 'Domestic',
    dispatch_by TEXT DEFAULT 'Customer',
    final_vehicle BOOLEAN DEFAULT false,
    lashing_driver BOOLEAN DEFAULT false,
    driver_details TEXT,
    verified_by TEXT,
    photos_by TEXT,
    created_by TEXT,
    voltage_range TEXT,
    dispatch_ref TEXT,
    packing_ref TEXT,
    loading_ref TEXT,
    delivery_deadline TEXT,
    mva TEXT,
    customer_inspection TEXT DEFAULT 'Pending',
    approved_by TEXT,
    approved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Packing Items Table
CREATE TABLE IF NOT EXISTS public.packing_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_id BIGINT REFERENCES public.work_orders(id) ON DELETE CASCADE,
    wo_num TEXT,
    box_num TEXT,
    item_num TEXT,
    description TEXT NOT NULL,
    custom_desc TEXT,
    vehicle TEXT,
    phone TEXT,
    qty INTEGER DEFAULT 1,
    uom TEXT,
    pack_type TEXT,
    status TEXT DEFAULT 'Not Started',
    weight NUMERIC DEFAULT 0,
    gross_weight NUMERIC DEFAULT 0,
    dimensions TEXT,
    height NUMERIC DEFAULT 0,
    length NUMERIC DEFAULT 0,
    width NUMERIC DEFAULT 0,
    production_sig TEXT,
    quality_sig TEXT,
    notes TEXT,
    packing_start_date DATE,
    packing_end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Loading Items Table
CREATE TABLE IF NOT EXISTS public.loading_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_id BIGINT REFERENCES public.work_orders(id) ON DELETE CASCADE,
    wo_num TEXT,
    item_num TEXT,
    description TEXT NOT NULL,
    vehicle TEXT,
    phone TEXT,
    qty INTEGER DEFAULT 1,
    uom TEXT,
    weight NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    notes TEXT,
    box_num TEXT,
    po_num TEXT,
    production_sig TEXT,
    quality_sig TEXT,
    lashing_status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num TEXT NOT NULL UNIQUE,
    type TEXT,
    wo_num TEXT,
    customer TEXT,
    driver TEXT,
    phone TEXT,
    shift TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Loading Lists Table (Master document for a dispatch)
CREATE TABLE IF NOT EXISTS public.loading_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ll_num TEXT NOT NULL UNIQUE,
    wo_id BIGINT REFERENCES public.work_orders(id) ON DELETE CASCADE,
    wo_num TEXT,
    customer_name TEXT,
    vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE SET NULL,
    vehicle_num TEXT,
    vehicle_type TEXT,
    driver_name TEXT,
    date_of_loading TEXT,
    status TEXT DEFAULT 'Loading Pending',
    vehicle_capacity NUMERIC DEFAULT 10000,
    wos_data JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Loading List Items Table (Items associated with a loading list)
CREATE TABLE IF NOT EXISTS public.loading_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ll_id BIGINT REFERENCES public.loading_lists(id) ON DELETE CASCADE,
    packing_item_id BIGINT REFERENCES public.packing_items(id) ON DELETE CASCADE,
    box_num TEXT,
    item_num TEXT,
    description TEXT NOT NULL,
    qty INTEGER DEFAULT 1,
    weight NUMERIC DEFAULT 0,
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 6. Stuff List Table
CREATE TABLE IF NOT EXISTS public.stuff_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    qty INTEGER DEFAULT 0,
    uom TEXT,
    status TEXT DEFAULT 'Available',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Master List Table (Categories and items)
CREATE TABLE IF NOT EXISTS public.master_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(category_key, value)
);

-- 8. Activity Log Table
CREATE TABLE IF NOT EXISTS public.activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Configuration

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.packing_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loading_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stuff_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loading_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loading_list_items ENABLE ROW LEVEL SECURITY;

-- Trigger function to manage packing dates with rollback handling
CREATE OR REPLACE FUNCTION public.handle_packing_dates()
RETURNS TRIGGER AS $$
BEGIN
    -- Transition Not Started -> In Progress
    IF NEW.status = 'In Progress' AND OLD.status = 'Not Started' THEN
        IF NEW.packing_start_date IS NULL THEN
            NEW.packing_start_date := CURRENT_DATE;
        END IF;
    END IF;
    -- Transition In Progress -> Packed
    IF NEW.status = 'Packed' AND OLD.status = 'In Progress' THEN
        IF NEW.packing_end_date IS NULL THEN
            NEW.packing_end_date := CURRENT_DATE;
        END IF;
    END IF;
    -- Rollback In Progress -> Not Started
    IF NEW.status = 'Not Started' AND OLD.status = 'In Progress' THEN
        NEW.packing_start_date := NULL;
    END IF;
    -- Rollback Packed -> In Progress
    IF NEW.status = 'In Progress' AND OLD.status = 'Packed' THEN
        NEW.packing_end_date := NULL;
    END IF;
    -- Direct rollback Packed -> Not Started (clear both)
    IF NEW.status = 'Not Started' AND OLD.status = 'Packed' THEN
        NEW.packing_start_date := NULL;
        NEW.packing_end_date := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger on packing_items
CREATE TRIGGER trg_handle_packing_dates
BEFORE UPDATE OF status ON public.packing_items
FOR EACH ROW EXECUTE FUNCTION public.handle_packing_dates();

-- Allow read access to authenticated users
CREATE POLICY "Allow authenticated read access" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.work_orders FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.packing_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.loading_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.vehicles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.stuff_list FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.master_list FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.activity_log FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.loading_lists FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read access" ON public.loading_list_items FOR SELECT USING (auth.role() = 'authenticated');

-- For simplicity in this iteration, we allow authenticated users to perform all operations.
-- Real RBAC logic can be enforced here by checking the profiles table.
CREATE POLICY "Allow authenticated all access" ON public.profiles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.work_orders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.packing_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.loading_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.vehicles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.stuff_list FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.master_list FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.activity_log FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.loading_lists FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated all access" ON public.loading_list_items FOR ALL USING (auth.role() = 'authenticated');
