-- Phase 2: Enterprise Guardrails Schema Updates

-- 1. ENUM types for status and roles
CREATE TYPE public.packing_status_enum AS ENUM ('Not Started','In Progress','Packed');
CREATE TYPE public.dispatch_status_enum AS ENUM ('Pending','Dispatched','Delivered','Cancelled');
CREATE TYPE public.user_role_enum AS ENUM ('SuperAdmin','DispatchAdmin','DashboardUser','NormalUser');

-- 2. Extend packing_items with dates and override audit fields
ALTER TABLE public.packing_items
    ADD COLUMN IF NOT EXISTS packing_start_date DATE,
    ADD COLUMN IF NOT EXISTS packing_end_date DATE,
    ADD COLUMN IF NOT EXISTS last_override_reason TEXT,
    ADD COLUMN IF NOT EXISTS last_override_by UUID,
    ADD COLUMN IF NOT EXISTS last_override_at TIMESTAMPTZ;

-- 3. Add audit columns to capture status changes (optional, can be stored in activity_log)
-- We'll store old/new status in activity_log for now

-- 4. Add CHECK constraints for status columns using ENUMs
ALTER TABLE public.packing_items
    ALTER COLUMN status SET DATA TYPE public.packing_status_enum USING status::public.packing_status_enum;
ALTER TABLE public.work_orders
    ALTER COLUMN status SET DATA TYPE public.dispatch_status_enum USING status::public.dispatch_status_enum;

-- 5. Add indexes for performance-critical queries
CREATE INDEX IF NOT EXISTS idx_packing_status ON public.packing_items (status);
CREATE INDEX IF NOT EXISTS idx_packing_created_by ON public.packing_items (created_by);
CREATE INDEX IF NOT EXISTS idx_loading_vehicle_number ON public.loading_lists (vehicle_number);
CREATE INDEX IF NOT EXISTS idx_work_orders_created_at ON public.work_orders (created_at);

-- 6. Dead‑letter queue table for failed async jobs
CREATE TABLE IF NOT EXISTS public.failed_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    retry_count INTEGER DEFAULT 0,
    failure_reason TEXT,
    failed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 7. Update trigger function set_packing_dates() to avoid overwriting existing dates
CREATE OR REPLACE FUNCTION public.set_packing_dates()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.status = 'In Progress' AND (OLD.status = 'Not Started' OR OLD.status IS NULL) THEN
            IF NEW.packing_start_date IS NULL THEN
                NEW.packing_start_date := CURRENT_DATE;
            END IF;
        END IF;
        IF NEW.status = 'Packed' AND (OLD.status = 'In Progress' OR OLD.status IS NULL) THEN
            IF NEW.packing_end_date IS NULL THEN
                NEW.packing_end_date := CURRENT_DATE;
            END IF;
        END IF;
        -- Rollback handling
        IF NEW.status = 'Not Started' AND OLD.status = 'In Progress' THEN
            NEW.packing_start_date := NULL;
            NEW.packing_end_date := NULL;
        ELSIF NEW.status = 'In Progress' AND OLD.status = 'Packed' THEN
            NEW.packing_end_date := NULL;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_packing_dates ON public.packing_items;
CREATE TRIGGER trg_set_packing_dates
AFTER UPDATE ON public.packing_items
FOR EACH ROW EXECUTE FUNCTION public.set_packing_dates();

-- 8. Update work_order_clone function to copy only active (not soft‑deleted) items and order by created_at ASC
CREATE OR REPLACE FUNCTION public.clone_work_order(p_source_wo_num TEXT, p_new_wo_num TEXT)
RETURNS VOID AS $$
DECLARE
    src_wo_id BIGINT;
BEGIN
    SELECT id INTO src_wo_id FROM public.work_orders WHERE wo_num = p_source_wo_num;
    IF src_wo_id IS NULL THEN
        RAISE EXCEPTION 'Source work order not found';
    END IF;
    -- Insert new work order (simplified)
    INSERT INTO public.work_orders (wo_num, customer, status, created_at)
    SELECT p_new_wo_num, customer, status, timezone('utc'::text, now())
    FROM public.work_orders WHERE id = src_wo_id;
    -- Clone packing items (only active, ordered)
    INSERT INTO public.packing_items (wo_id, wo_num, box_num, item_num, description, qty, uom, status, created_at)
    SELECT (SELECT id FROM public.work_orders WHERE wo_num = p_new_wo_num),
           p_new_wo_num,
           box_num, item_num, description, qty, uom, status, timezone('utc'::text, now())
    FROM public.packing_items
    WHERE wo_id = src_wo_id AND is_deleted = FALSE
    ORDER BY created_at ASC;
END;
$$ LANGUAGE plpgsql;

-- 9. Dashboard metrics function with max date range guard (365 days)
CREATE OR REPLACE FUNCTION public.dashboard_metrics(p_start DATE, p_end DATE)
RETURNS JSONB AS $$
BEGIN
    IF p_end - p_start > INTERVAL '365 days' THEN
        RAISE EXCEPTION 'Date range cannot exceed 365 days';
    END IF;
    RETURN jsonb_build_object(
        'packing_counts', (SELECT jsonb_agg(row_to_json(t)) FROM (
            SELECT status, COUNT(*) AS cnt FROM public.packing_items WHERE created_at BETWEEN p_start AND p_end GROUP BY status
        ) t),
        'work_order_counts', (SELECT jsonb_agg(row_to_json(t)) FROM (
            SELECT status, COUNT(*) AS cnt FROM public.work_orders WHERE created_at BETWEEN p_start AND p_end GROUP BY status
        ) t)
    );
END;
$$ LANGUAGE plpgsql;

-- 10. Role helper function for RLS
CREATE OR REPLACE FUNCTION public.has_role(uid UUID, role TEXT)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM public.profiles WHERE id = uid AND role = role);
END;
$$ LANGUAGE plpgsql;

-- 11. Update RLS policies to use has_role (example for work_orders)
DROP POLICY IF EXISTS work_orders_role_policy ON public.work_orders;
CREATE POLICY work_orders_role_policy ON public.work_orders
    FOR ALL TO public
    USING (public.has_role(auth.uid(), 'SuperAdmin') OR public.has_role(auth.uid(), 'DispatchAdmin') OR public.has_role(auth.uid(), 'DashboardUser') OR public.has_role(auth.uid(), 'NormalUser'));

-- Note: Adjust other tables similarly.

-- End of Phase 2 migration
